Repository akheron/sqltyper, pull requests merged in 2021-09, with the labels that each got.

#274 Upgrade jest
  package.json
  yarn.lock
Labels: chore

#281 CI: Run tests on NodeJS 16.x and not 15.x
  .github/workflows/tests.yml
Labels: chore

#284 Named params must start with a letter
  src/preprocess.ts
Labels: fix

#293 Support more typecast syntaxes
  src/parser/index.ts
  src/parser/token.ts
  src/parser/typecasts.ts
  src/tstype.ts
  tests/integration/constants.sql
Labels: fix

#316 Allow UPDATE alias to not have AS
  src/parser/index.ts
Labels: bug

#321 Fix INSERT row count when there's no RETURNING
  src/infer.ts
  tests/integration/delete.sql
  tests/integration/insert.sql
  tests/integration/update.sql
Labels: fix
